version: "3"


services:
  db-world:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coursesdb
    volumes:
      - db-data-940123:/var/lib/postgresql/data

volumes:
  db-data-940123: